export const LOADING_RESERVE = "LOADING_RESERVE";
export const ERROR_RESERVE = "ERROR_RESERVE";

export const GET_RESERVE_LIST = "GET_RESERVE_LIST";

export const CREATE_RESERVE_LIST = "CREATE_RESERVE_LIST";
export const UPDATE_RESERVE_LIST = "UPDATE_RESERVE_LIST";
export const DELETE_RESERVE_LIST = "DELETE_RESERVE_LIST";
